apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vascolb01
  name: vascolb01
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: vasco-finalapp
  type: NodePort
status:
  loadBalancer: {}
